// Phase 6, Exercise 2 — Move Semantics Buffer
// Concept: rvalue references, std::move, move constructor, move assignment.
// Demonstrates: std::byte[], moved-from state, noexcept move.
//
// Move semantics (C++11) allow transferring resources from temporaries and
// "soon-to-be-destroyed" objects instead of copying them. This is zero-cost
// for heap resources: pointer copy + null-out vs deep allocation.
//
// Key mental model:
//   std::move(x) — a CAST, not a move. It converts x to an rvalue reference.
//                  The actual move happens in the move constructor/assignment.
//   T&& — rvalue reference. Binds to temporaries and std::move(x).
//   T&  — lvalue reference. Binds to named objects (non-temporary).
//
// For a type with all movable members, '= default' move operations are
// generated by the compiler. This class shows the MANUAL version so you can
// see exactly what happens.

#pragma once

#include <cstddef>   // std::size_t, std::byte
#include <utility>   // std::exchange

class Buffer {
public:
    explicit Buffer(std::size_t size);
    ~Buffer();

    // Copy operations — included for completeness (see Phase 3 Ex2).
    Buffer(const Buffer& other);
    Buffer& operator=(const Buffer& other);

    // ── Move Constructor ──────────────────────────────────────────────────────
    // noexcept is critical here: if the move constructor could throw, standard
    // containers like std::vector fall back to copying (they can't offer the
    // strong exception guarantee with a throwing move). Always mark moves noexcept.
    Buffer(Buffer&& other) noexcept;

    // ── Move Assignment ───────────────────────────────────────────────────────
    Buffer& operator=(Buffer&& other) noexcept;

    std::byte*       data()  noexcept { return data_; }
    const std::byte* data()  const noexcept { return data_; }
    std::size_t      size()  const noexcept { return size_; }

    // After a move, the buffer is in the "moved-from" state: data_ == nullptr,
    // size_ == 0. This predicate lets tests verify the moved-from state.
    bool is_moved_from() const noexcept { return data_ == nullptr; }

private:
    std::byte*  data_;
    std::size_t size_;
};
